var camp;
camp = {};
camp.data = [{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Herring Reservoir',
	description: '',
	location: new google.maps.LatLng(38.244496, -119.932938),
	scenicRating: 8,
	elevation: 7350,
	sites: true,
	numOfSites: 42,
	perSiteCost: 'free',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Pioneer Trail Group Camp',
	description: '',
	location: new google.maps.LatLng(38.19204, -119.99255),
	scenicRating: 8,
	elevation: 5700,
	sites: true,
	numOfSites: 200,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 3,
	sizeOfGroupSites: '50-100',
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$80-$120'
},{
	name: 'Cherry Lake',
	description: '',
	location: new google.maps.LatLng(37.97704, -119.91958),
	scenicRating: 8,
	elevation: 4700,
	sites: true,
	numOfSites: 45,
	perSiteCost: '$19',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Tamarack Flat',
	description: 'In Yosemite',
	location: new google.maps.LatLng(37.75158, -119.73631),
	scenicRating: 7,
	elevation: 6300,
	sites: true,
	numOfSites: 52,
	perSiteCost: '$10',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Tuolumne Meadows',
	description: '',
	location: new google.maps.LatLng(37.871055, -119.361056),
	scenicRating: 8,
	elevation: 8600,
	sites: true,
	numOfSites: 304,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 7,
	sizeOfGroupSites: '30',
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$40'
},{
	name: 'Lower Pines Yosemite',
	description: '',
	location: new google.maps.LatLng(37.73926, -119.56583),
	scenicRating: 9,
	elevation: 4000,
	sites: true,
	numOfSites: 60,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 2,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$30'
},{
	name: 'Upper Pines Yosemite',
	description: '',
	location: new google.maps.LatLng(37.73615, -119.56372),
	scenicRating: 9,
	elevation: 4000,
	sites: true,
	numOfSites: 238,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'North Pines Yosemite',
	description: '',
	location: new google.maps.LatLng(37.74164, -119.56628),
	scenicRating: 9,
	elevation: 4000,
	sites: true,
	numOfSites: 81,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Bridalveil Creek and Group Camp',
	description: 'Close to Glacier Point. Has Camp sites, Equestrian Sites, and Group Sites.',
	location: new google.maps.LatLng(37.66222, -119.62090),
	scenicRating: 10,
	elevation: 7200,
	sites: true,
	numOfSites: 110,
	perSiteCost: '$14',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 2,
	sizeOfGroupSites: '13-30',
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$40'
},{
	name: 'Wawona',
	description: 'Group Site is for tent only. Golfing.',
	location: new google.maps.LatLng(37.53630, -119.65597),
	scenicRating: 9,
	elevation: -1,
	sites: true,
	numOfSites: 93,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 1,
	sizeOfGroupSites: '13-30',
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$40'
},{
	name: 'Merced Recreation Area',
	description: 'Rafting, Kayaking, fishing along the Merced River. Tom Stienstra\'s best pick (California Camping Guide).',
	location: new google.maps.LatLng(37.596909, -120.003386),
	scenicRating: 8,
	elevation: -1,
	sites: true,
	numOfSites: '21 walk-in + 9 standard',
	perSiteCost: '$10',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Fresno Dome',
	description: '',
	location: new google.maps.LatLng(37.45599, -119.54906),
	scenicRating: 7,
	elevation: 6400,
	sites: true,
	numOfSites: 15,
	perSiteCost: '$17 single, $34 double,  + $5 per additional vehicle',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Nelder Grove',
	description: 'Near Nelder Grove Giant Sequoias. RVs up to 20 ft. Primitive.',
	location: new google.maps.LatLng(37.412563, -119.587070),
	scenicRating: 7,
	elevation: 5300,
	sites: true,
	numOfSites: 7,
	perSiteCost: 'free',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Upper Chiquio',
	description: '',
	location: new google.maps.LatLng(37.50219, -119.41050),
	scenicRating: 7,
	elevation: 6800,
	sites: true,
	numOfSites: 20,
	perSiteCost: 'free',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Clover Meadow',
	description: 'Jump-off point for backpacking. RVs up to 20 ft',
	location: new google.maps.LatLng(37.52857, -119.28077),
	scenicRating: 8,
	elevation: 7000,
	sites: true,
	numOfSites: 7,
	perSiteCost: 'free',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},,{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
}]
window.camp = camp;