var camp;
camp = {};
camp.data = [{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Herring Reservoir',
	description: '',
	location: new google.maps.LatLng(38.244496, -119.932938),
	scenicRating: 8,
	elevation: 7350,
	sites: true,
	numOfSites: 42,
	perSiteCost: 'free',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Pioneer Trail Group Camp',
	description: '',
	location: new google.maps.LatLng(38.19204, -119.99255),
	scenicRating: 8,
	elevation: 5700,
	sites: true,
	numOfSites: 200,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 3,
	sizeOfGroupSites: '50-100',
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$80-$120'
},{
	name: 'Cherry Lake',
	description: '',
	location: new google.maps.LatLng(37.97704, -119.91958),
	scenicRating: 8,
	elevation: 4700,
	sites: true,
	numOfSites: 45,
	perSiteCost: '$19',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Tamarack Flat',
	description: 'In Yosemite',
	location: new google.maps.LatLng(37.75158, -119.73631),
	scenicRating: 7,
	elevation: 6300,
	sites: true,
	numOfSites: 52,
	perSiteCost: '$10',
	sitesAcceptReservations: false,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Tuolumne Meadows',
	description: '',
	location: new google.maps.LatLng(37.871055, -119.361056),
	scenicRating: 8,
	elevation: 8600,
	sites: true,
	numOfSites: 304,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 7,
	sizeOfGroupSites: '30',
	groupSitesAcceptReservations: true,
	perGroupSiteCost: '$40'
},{
	name: 'Lower Pines Yosemite',
	description: '',
	location: new google.maps.LatLng(37.73926, -119.56583),
	scenicRating: 9,
	elevation: 4000,
	sites: true,
	numOfSites: 60,
	perSiteCost: '$20',
	sitesAcceptReservations: true,
	groupSites: false,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
},{
	name: 'Template',
	description: '',
	location: new google.maps.LatLng(0,0),
	scenicRating: 0,
	elevation: 0,
	sites: true,
	numOfSites: 0,
	perSiteCost: '',
	sitesAcceptReservations: true,
	groupSites: true,
	numOfGroupSites: 0,
	sizeOfGroupSites: 0,
	groupSitesAcceptReservations: true,
	perGroupSiteCost: ''
}]
window.camp = camp;